InputSummary.create!([
  {summary_name: "view実装", snippet_id: 3},
  {summary_name: "テスト実装", snippet_id: 3},
  {summary_name: "モデル実装", snippet_id: 3},
  {summary_name: "js", snippet_id: 5},
  {summary_name: "controller", snippet_id: 5},
  {summary_name: "formObject", snippet_id: 5},
  {summary_name: "view", snippet_id: 5},
  {summary_name: "その他", snippet_id: 5},
  {summary_name: "test", snippet_id: 5},
  {summary_name: "ユーザー", snippet_id: 6},
  {summary_name: "商品", snippet_id: 6},
  {summary_name: "購入履歴", snippet_id: 6},
  {summary_name: "配送先住所", snippet_id: 6},
  {summary_name: "controller", snippet_id: 8},
  {summary_name: "その他", snippet_id: 6},
  {summary_name: "view", snippet_id: 10},
  {summary_name: "issue1~3", snippet_id: 11},
  {summary_name: "issue4~6", snippet_id: 11},
  {summary_name: "その他", snippet_id: 11},
  {summary_name: "その他", snippet_id: 4},
  {summary_name: "テスト", snippet_id: 4},
  {summary_name: "指摘", snippet_id: 12},
  {summary_name: "LGTM", snippet_id: 12},
  {summary_name: "view", snippet_id: 13},
  {summary_name: "controller", snippet_id: 14},
  {summary_name: "model", snippet_id: 4}
])
